
[functions.start-quizit-session]
enabled = true
verify_jwt = true
import_map = "./functions/start-quizit-session/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/start-quizit-session/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/start-quizit-session/*.html" ]

[functions.next-quizit-items]
enabled = true
verify_jwt = true
import_map = "./functions/next-quizit-items/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/next-quizit-items/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/next-quizit-items/*.html" ]
